# Generated by Django 3.1.4 on 2021-01-09 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remembercards',
            options={'verbose_name': 'Воспоминание', 'verbose_name_plural': 'Воспоминания'},
        ),
        migrations.RemoveField(
            model_name='remembercards',
            name='mpoly',
        ),
    ]
