# Generated by Django 3.1.4 on 2021-01-08 09:36

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remembers', '0002_auto_20210108_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remembercards',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326),
        ),
    ]
